[package]
name = "entity_main"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "entity_main"
path = "src/mod.rs"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }

[dependencies.sea-orm]
version = "2.0.0-rc"